version: '3.4'

services:
  #moloch-capture:
  #  build: .
  #  entrypoint: ./docker-entrypoint-capture.sh
  #  volumes:
  #    - "/data/moloch/raw:/data/moloch/raw"
  moloch-viewer:
    build: .
    ports:
      - 80:8005
    entrypoint: ./docker-entrypoint-viewer.sh
    volumes:
      - "/data/moloch/raw:/data/moloch/raw"
  elasticsearch:
    image: elasticsearch:6.8.3
