version: '3'
services:
  moloch:
    build: .
    ports:
      - 8005:8005
    volumes:
      - "/pcaps:/data/moloch/raw"
    environment:
      - "MOLOCH_PASSWORD=keks"
  elasticsearchmoloch:
    image: elasticsearch:7.6.0
    environment:
      - discovery.type=single-node
      # should be half of the available RAM
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
