version: '3'
services:
  moloch:
    build: .
    ports:
      - 8005:8005
    volumes:
      - "/pcaps:/data/moloch/raw"
    environment:
      - "MOLOCH_PASSWORD=keks"
  elasticsearchmoloch:
    image: elasticsearch:6.8.5
