version: '3'
services:
  moloch:
    build: .
    ports:
      - 8005:8005
    volumes:
      - "./pcaps:/opt/arkime/raw"
  elasticsearchmoloch:
    image: elasticsearch:7.14.2
    environment:
      - discovery.type=single-node
# pluginsDir=/opt/arkime/plugins
