version: '3'
services:
  moloch-viewer:
    #build: .
    image: enoflag/enomoloch
    ports:
      - 8005:8005
    volumes:
      - "./pcaps:/data/moloch/raw"
      - "./config.ini:/data/moloch/etc/config.ini"
    entrypoint: ./docker-viewer.sh
    depends_on: 
      - elasticsearchmoloch
      - init-db

  init-db:
    #build: .
    image: enoflag/enomoloch
    entrypoint: ./elasticsearch_init.sh
    depends_on: 
      - elasticsearchmoloch
    environment:
      - "MOLOCH_USER=changeme"
      - "MOLOCH_PASSWORD=changeme"
    
  moloch-capture:
    #build: .
    image: enoflag/enomoloch
    volumes:
     - "./pcaps:/data/moloch/raw"
     - "./config.ini:/data/moloch/etc/config.ini"
     #- "../target/debug/libenoxploit_moloch.so:/data/moloch/plugins/libenoxploit_moloch.so"
    entrypoint: ./moloch-capture.sh
    depends_on: 
      - elasticsearchmoloch
      - init-db

  elasticsearchmoloch:
    image: elasticsearch:7.6.2
    environment:
      - discovery.type=single-node
      # should be half of the available RAM
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/db:/usr/share/elasticsearch/data

