name: Docker Nightly

on:
  pull_request:
    # Publish `master` as Docker `latest` image.
    branches:
      - main
      - master

env:
  IMAGE_NAME: enoarkime

jobs:
  # Push image to GitHub Packages.
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          docker image build .
